services:
  postgres1:
    image: postgres:15
    container_name: postgres_shard_1
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
    networks:
      - sharding_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin1 -d database1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres2:
    image: postgres:15
    container_name: postgres_shard_2
    environment:
      POSTGRES_DB: database2
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: password456
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data
    networks:
      - sharding_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin2 -d database2"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres3:
    image: postgres:15
    container_name: postgres_shard_3
    environment:
      POSTGRES_DB: database3
      POSTGRES_USER: admin3
      POSTGRES_PASSWORD: password789
    ports:
      - "5434:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data
    networks:
      - sharding_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin3 -d database3"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:

networks:
  sharding_network:
    driver: bridge